---
### REQUIRED

# The namespace of the collection. This can be a company/brand/organization or product namespace under which all
# content lives. May only contain alphanumeric characters and underscores. Additionally namespaces cannot start with
# underscores or numbers and cannot contain consecutive underscores
namespace: dbmruphy

# The name of the collection. Has the same character restrictions as 'namespace'
name: cis_security

# The version of the collection. Must be compatible with semantic versioning
version: 2.0.0

# The path to the Markdown (.md) readme file. This path is relative to the root of the collection
readme: README.md

# A list of the collection's content authors. Can be just the name or in the format 'Full Name <email> (url)
# @nicks:irc/im.site#channel'
authors:
  - David Glaser <dsglaser@gmail.com>
  - David Murphy <david.b.murphy.tx@gmail.com>

### OPTIONAL but strongly recommended

# A short summary description of the collection
description: A collection to implement Center for Internet Security (CIS) controls for RHEL, CentOS, OracleLinux, AmazonLinux2, Ubuntu, SLES 15, and Windows based
  on dsgraser/cis-security

# Either a single license or a list of licenses for content inside of a collection. Ansible Galaxy currently only
# accepts L(SPDX,https://spdx.org/licenses/) licenses. This key is mutually exclusive with 'license_file'
license:
# The path to the license file for the collection. This path is relative to the root of the collection. This key is
# mutually exclusive with 'license'
license_file: LICENSE

# A list of tags you want to associate with the collection for indexing/searching. A tag name has the same character
# requirements as 'namespace' and 'name'
tags: [system, security]
# Collections that this collection requires to be installed for it to be usable. The key of the dict is the
# collection label 'namespace.name'. The value is a version range
# L(specifiers,https://python-semanticversion.readthedocs.io/en/latest/#requirement-specification). Multiple version
# range specifiers can be set and are separated by ','
dependencies:
  community.general: "*"
  community.windows: "*"

# The URL of the originating SCM repository
repository: https://github.com/dbmurphy/cis-security

# The URL to any online docs
#documentation: http://docs.example.com

# The URL to the homepage of the collection/project
#homepage: http://example.com

# The URL to the collection issue tracker
issues: https://github.com/dbmurphy/cis-security/issues
